title: Benjamin Zhang # Your name or website title here
logo: "/images/photo_cartoon_circle.png?raw=true" # Your photo (or logo) here
description: > # Your text below
  <p style="font-size:18px; line-height: 1.6;">
  <strong>MS in Data Science</strong> <br />
  <strong>PhD in Neuroscience</strong> <br/><br/>
  Hello, I'm Ben! Iâ€™m deeply passionate about uncovering insights from complex, real-world data to spark innovation and improve healthcare.
  </p>
  <br><br>
  <!-- Social Media Icons -->
  <div style="display:flex; justify-content:left; gap:15px;">
    <a href="https://www.linkedin.com/in/BZhang8/" target="_blank" style="font-size:14px; color:#0277BD;">
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="LinkedIn" style="width:40px; height:40px;" />
    </a>
    <a href="https://github.com/Benjamin2009" target="_blank" style="font-size:14px; color:#0277BD;">
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" alt="GitHub" style="width:40px; height:40px;" />
    </a>
  </div>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # Your Google Analytics tracking ID here

